apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: alpine
    name: test
    command: ["/bin/sh", "-c", "while true; do printenv; sleep 5; done"]
    env:
    - name: TEST_ENV_VAR
      valueFrom:
        configMapKeyRef:
          name: test-config
          key: var
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  var: "Hello, Config Map!"