apiVersion: v1
kind: Pod
metadata:
  name: live-test
spec:
  containers:
  - name: live
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      httpGet:
        path: /
        port: http