apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
      - name: shared
        emptyDir: {}
      containers:
      - image: alpine
        name: producer
        readinessProbe:
          exec:
            command:
            - cat
            - /shared/queue/message.txt
          initialDelaySeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /shared/queue/message.txt
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: shared
          mountPath: /shared
        command: ["/bin/sh", "-c", "set -eu; mkdir -p /shared/queue; echo \"Hello from producer on $(date -u +'%Y-%m-%dT%H:%M:%SZ')\" > /shared/queue/message.txt; echo 'Producer wrote:'; cat /shared/queue/message.txt; tail -f /dev/null"]
      - image: alpine
        name: consumer
        readinessProbe:
          exec:
            command:
            - cat
            - /shared/queue/message.txt
          initialDelaySeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /shared/queue/message.txt
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: shared
          mountPath: /shared
        command: ["/bin/sh", "-c", "set -eu; echo 'Consumer waiting for message...'; while [ ! -f /shared/queue/message.txt ]; do sleep 1; done; echo 'Consumer read:'; cat /shared/queue/message.txt; tail -f /dev/null"]