version: "3.9"

services:
  producer:
    image: alpine:3.19
    restart: always
    volumes:
      - shared:/shared/queue
    entrypoint: ["/bin/sh", "-c"]
    command: [""]
  consumer:
    image: alpine:3.19
    restart: always
    volumes:
      - shared:/shared/queue
    entrypoint: ["/bin/sh", "-c"]
    command: [""]

volumes:
  shared: